CREATE TABLE salesperson (
      id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    , name varchar(255)
    , age int
    , salary int
);

INSERT INTO salesperson (id, name, age, salary) VALUES 
  ( 1, 'Abe',   61, 140000)
, ( 2, 'Bob',   34,  44000)
, ( 5, 'Chris', 34,  40000)
, ( 7, 'Dan',   41,  52000)
, ( 8, 'Ken',   57, 115000)
, (11, 'Joe',   38,  38000)
;

CREATE TABLE customer (
      id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    , name varchar(255)
    , city varchar(255)
    , industry_type varchar(1)
);

INSERT INTO customer (id, name, city, industry_type) VALUES
  (4, 'Samsonic', 'pleasant', 'J')
, (6, 'Panasung', 'oaktown',  'J')
, (7, 'Samony',   'jackson',  'B')
, (9, 'Orange',   'jackson',  'B')
;

CREATE TABLE orders (
      number int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY
    , order_date date
    , cust_id int
    , salesperson_id int
    , amount int
    , CONSTRAINT fk_customer FOREIGN KEY(cust_id) REFERENCES customer(id)
    , CONSTRAINT fk_salesperson FOREIGN KEY(salesperson_id) REFERENCES salesperson(id)
);

INSERT INTO orders (number, order_date, cust_id, salesperson_id, amount) VALUES
  (10, '19960802', 4, 2,  540)
, (20, '19990130', 4, 8, 1800)
, (30, '19950714', 9, 1,  460)
, (40, '19980129', 7, 2, 2400)
, (50, '19980203', 6, 7,  600)
, (60, '19980302', 6, 7,  720)
, (70, '19980506', 9, 7,  150)
;
